apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tjvp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-tjvp@sha256:007c40334cdce89412bef68c24b3293d1906c6c72b61d0597c03cef9dd88ffe4
        name: my-nodejs
        resources: {}
status: {}
